//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ball {
            get {
                object obj = ResourceManager.GetObject("Ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck01 {
            get {
                object obj = ResourceManager.GetObject("Duck01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck02 {
            get {
                object obj = ResourceManager.GetObject("Duck02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck03 {
            get {
                object obj = ResourceManager.GetObject("Duck03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck11 {
            get {
                object obj = ResourceManager.GetObject("Duck11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck12 {
            get {
                object obj = ResourceManager.GetObject("Duck12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck13 {
            get {
                object obj = ResourceManager.GetObject("Duck13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck21 {
            get {
                object obj = ResourceManager.GetObject("Duck21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck22 {
            get {
                object obj = ResourceManager.GetObject("Duck22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck23 {
            get {
                object obj = ResourceManager.GetObject("Duck23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck31 {
            get {
                object obj = ResourceManager.GetObject("Duck31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck32 {
            get {
                object obj = ResourceManager.GetObject("Duck32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck33 {
            get {
                object obj = ResourceManager.GetObject("Duck33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck41 {
            get {
                object obj = ResourceManager.GetObject("Duck41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck42 {
            get {
                object obj = ResourceManager.GetObject("Duck42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Duck43 {
            get {
                object obj = ResourceManager.GetObject("Duck43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit_Sign {
            get {
                object obj = ResourceManager.GetObject("Exit_Sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Level&gt;&lt;brick&gt;&lt;x&gt;43&lt;/x&gt;&lt;y&gt;239&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;98&lt;/x&gt;&lt;y&gt;239&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;98&lt;/x&gt;&lt;y&gt;274&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;153&lt;/x&gt;&lt;y&gt;274&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;153&lt;/x&gt;&lt;y&gt;309&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;208&lt;/x&gt;&lt;y&gt;309&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;208&lt;/x&gt;&lt;y&gt;344&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;263&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameLevel1 {
            get {
                return ResourceManager.GetString("GameLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Level&gt;&lt;brick&gt;&lt;x&gt;64&lt;/x&gt;&lt;y&gt;66&lt;/y&gt;&lt;hp&gt;2&lt;/hp&gt;&lt;color&gt;DarkCyan&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;64&lt;/x&gt;&lt;y&gt;101&lt;/y&gt;&lt;hp&gt;2&lt;/hp&gt;&lt;color&gt;DarkCyan&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;64&lt;/x&gt;&lt;y&gt;136&lt;/y&gt;&lt;hp&gt;2&lt;/hp&gt;&lt;color&gt;DarkCyan&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;64&lt;/x&gt;&lt;y&gt;171&lt;/y&gt;&lt;hp&gt;2&lt;/hp&gt;&lt;color&gt;DarkCyan&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;64&lt;/x&gt;&lt;y&gt;206&lt;/y&gt;&lt;hp&gt;2&lt;/hp&gt;&lt;color&gt;DarkCyan&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;64&lt;/x&gt;&lt;y&gt;241&lt;/y&gt;&lt;hp&gt;2&lt;/hp&gt;&lt;color&gt;DarkCyan&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;64&lt;/x&gt;&lt;y&gt;276&lt;/y&gt;&lt;hp&gt;2&lt;/hp&gt;&lt;color&gt;DarkCyan&lt;/color&gt;&lt;/brick [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameLevel2 {
            get {
                return ResourceManager.GetString("GameLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;251&lt;/x&gt;
        ///		&lt;y&gt;61&lt;/y&gt;
        ///		&lt;hp&gt;3&lt;/hp&gt;
        ///		&lt;color&gt;Orange&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;252&lt;/x&gt;
        ///		&lt;y&gt;96&lt;/y&gt;
        ///		&lt;hp&gt;3&lt;/hp&gt;
        ///		&lt;color&gt;Orange&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;252&lt;/x&gt;
        ///		&lt;y&gt;131&lt;/y&gt;
        ///		&lt;hp&gt;3&lt;/hp&gt;
        ///		&lt;color&gt;Orange&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;252&lt;/x&gt;
        ///		&lt;y&gt;166&lt;/y&gt;
        ///		&lt;hp&gt;3&lt;/hp&gt;
        ///		&lt;color&gt;Orange&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;252&lt;/x&gt;
        ///		&lt;y&gt;201&lt;/y&gt;
        ///		&lt;hp&gt;3&lt;/hp&gt;
        ///		&lt;color&gt;Orange&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;252&lt;/x&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameLevel3 {
            get {
                return ResourceManager.GetString("GameLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Level&gt;&lt;brick&gt;&lt;x&gt;10&lt;/x&gt;&lt;y&gt;75&lt;/y&gt;&lt;hp&gt;4&lt;/hp&gt;&lt;color&gt;Purple&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;10&lt;/x&gt;&lt;y&gt;110&lt;/y&gt;&lt;hp&gt;4&lt;/hp&gt;&lt;color&gt;Purple&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;10&lt;/x&gt;&lt;y&gt;145&lt;/y&gt;&lt;hp&gt;4&lt;/hp&gt;&lt;color&gt;Purple&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;10&lt;/x&gt;&lt;y&gt;180&lt;/y&gt;&lt;hp&gt;4&lt;/hp&gt;&lt;color&gt;Purple&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;10&lt;/x&gt;&lt;y&gt;215&lt;/y&gt;&lt;hp&gt;4&lt;/hp&gt;&lt;color&gt;Purple&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;10&lt;/x&gt;&lt;y&gt;250&lt;/y&gt;&lt;hp&gt;4&lt;/hp&gt;&lt;color&gt;Purple&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;10&lt;/x&gt;&lt;y&gt;285&lt;/y&gt;&lt;hp&gt;4&lt;/hp&gt;&lt;color&gt;Purple&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;10&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameLevel4 {
            get {
                return ResourceManager.GetString("GameLevel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Level&gt;&lt;brick&gt;&lt;x&gt;264&lt;/x&gt;&lt;y&gt;60&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;264&lt;/x&gt;&lt;y&gt;95&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;264&lt;/x&gt;&lt;y&gt;130&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;264&lt;/x&gt;&lt;y&gt;165&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;264&lt;/x&gt;&lt;y&gt;200&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;264&lt;/x&gt;&lt;y&gt;235&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;264&lt;/x&gt;&lt;y&gt;270&lt;/y&gt;&lt;hp&gt;1&lt;/hp&gt;&lt;color&gt;Green&lt;/color&gt;&lt;/brick&gt;&lt;brick&gt;&lt;x&gt;264&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameLevel5 {
            get {
                return ResourceManager.GetString("GameLevel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Level&gt;
        ///	
        ///&lt;/Level&gt;.
        /// </summary>
        internal static string LevelEditorXML {
            get {
                return ResourceManager.GetString("LevelEditorXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paddle {
            get {
                object obj = ResourceManager.GetObject("Paddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Reload {
            get {
                return ResourceManager.GetStream("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Shot {
            get {
                return ResourceManager.GetStream("Shot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sign {
            get {
                object obj = ResourceManager.GetObject("Sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;84&lt;/x&gt;
        ///		&lt;y&gt;120&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;84&lt;/x&gt;
        ///		&lt;y&gt;155&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;84&lt;/x&gt;
        ///		&lt;y&gt;190&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;84&lt;/x&gt;
        ///		&lt;y&gt;225&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;84&lt;/x&gt;
        ///		&lt;y&gt;260&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;84&lt;/x&gt;
        ///		&lt;y&gt;295&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserLevel1 {
            get {
                return ResourceManager.GetString("UserLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;121&lt;/x&gt;
        ///		&lt;y&gt;110&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;176&lt;/x&gt;
        ///		&lt;y&gt;110&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;231&lt;/x&gt;
        ///		&lt;y&gt;110&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;286&lt;/x&gt;
        ///		&lt;y&gt;110&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;341&lt;/x&gt;
        ///		&lt;y&gt;110&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;396&lt;/x&gt;
        ///		&lt;y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserLevel2 {
            get {
                return ResourceManager.GetString("UserLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;206&lt;/x&gt;
        ///		&lt;y&gt;145&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;261&lt;/x&gt;
        ///		&lt;y&gt;145&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;316&lt;/x&gt;
        ///		&lt;y&gt;145&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;371&lt;/x&gt;
        ///		&lt;y&gt;145&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;426&lt;/x&gt;
        ///		&lt;y&gt;145&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;151&lt;/x&gt;
        ///		&lt;y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserLevel3 {
            get {
                return ResourceManager.GetString("UserLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;145&lt;/x&gt;
        ///		&lt;y&gt;413&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;402&lt;/x&gt;
        ///		&lt;y&gt;445&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///&lt;/Level&gt;.
        /// </summary>
        internal static string UserLevel4 {
            get {
                return ResourceManager.GetString("UserLevel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;312&lt;/x&gt;
        ///		&lt;y&gt;531&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;391&lt;/x&gt;
        ///		&lt;y&gt;537&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///		&lt;color&gt;Green&lt;/color&gt;
        ///	&lt;/brick&gt;
        ///&lt;/Level&gt;.
        /// </summary>
        internal static string UserLevel5 {
            get {
                return ResourceManager.GetString("UserLevel5", resourceCulture);
            }
        }
    }
}
